name: Leo Liang's Organization CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  caling-reuse-workflow-in-dot-github:
    uses: .github/workflows/workflow-1.yml@master
